core/urls.py
from django.conf.urls.static import static
from django.urls import path

from projeto import settings
from . import views

app_name = 'core'

urlpatterns = [
                  path('', views.RedirecAuthenticationView.as_view(), name='redirect_authentication'),
                  path('login/', views.LoginView.as_view(), name='login'),
                  path('logout/', views.LogoutRedirectViews.as_view(), name='logout'),
                  path('store/list/', views.StoreListView.as_view(), name='store_list_view'),
                  path('store/import/create/', views.ImportFileCreateView.as_view(), name='store_import_create_view'),
              ] + static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),

]

core/models.py
from decimal import Decimal

from django.db import models
from django.db.models import Sum


def create_path_import_file(instance, filename):
    directory = 'file/import/'
    full_path = str(directory) + "/%s" % (filename)
    return full_path


OperationChocie = (
    ('ENTRADA', '+'),
    ('SAIDA', '-'),
)


class TimestampableMixin(models.Model):
    data_cadastro = models.DateTimeField(auto_now_add=True)
    date_modificado = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        abstract = True


class Owner(TimestampableMixin):
    document = models.CharField(max_length=18, null=True, unique=True)
    name = models.CharField(max_length=120)


class Company(TimestampableMixin):
    owner = models.ForeignKey(Owner, on_delete=models.PROTECT, null=True)
    name = models.CharField(max_length=120)

    @property
    def total_imports(self):
        return self.transactions.all().values_list('file__id', flat=True).distinct().count()

    @property
    def total_in(self):
        return self.transactions.filter(type__operation='ENTRADA').count()

    @property
    def total_out(self):
        return self.transactions.filter(type__operation='SAIDA').count()

    @property
    def total_balance(self):
        sum = self.transactions.filter(type__operation='ENTRADA').aggregate(Sum('value'))
        sub = self.transactions.filter(type__operation='SAIDA').aggregate(Sum('value'))
        sum = sum.get('value__sum') if sum.get('value__sum') else 0
        sub =  sub.get('value__sum') if  sub.get('value__sum') else 0
        total = sum - sub
        return Decimal(sum - sub)


class TransactionType(models.Model):
    cod = models.IntegerField(unique=True)
    description = models.CharField(max_length=255)
    operation = models.CharField(max_length=10, choices=OperationChocie)


class ImportCNAB(TimestampableMixin):
    file = models.FileField(upload_to=create_path_import_file)


class TransactionStore(TimestampableMixin):
    type = models.ForeignKey(TransactionType, on_delete=models.PROTECT)
    store = models.ForeignKey(Company, on_delete=models.PROTECT, related_name='transactions')
    file = models.ForeignKey(ImportCNAB, on_delete=models.PROTECT, null=True, blank=True)
    date = models.DateTimeField()
    value = models.DecimalField(max_digits=15, decimal_places=2)
    number_card = models.CharField(max_length=20, null=True)

core/forms.py
from datetime import datetime, timedelta
from time import strftime
from django import forms

from core.models import ImportCNAB


class ImportCNABForm(forms.ModelForm):
    class Meta:
        model = ImportCNAB
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ImportCNABForm, self).__init__(*args, **kwargs)

core/views.py
import codecs

from django.contrib import messages
from django.contrib.auth import login as django_login, logout

from django.contrib.auth import authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, CreateView, RedirectView
from extra_views import SearchableListMixin
from core.models import Company, ImportCNAB


class RedirecAuthenticationView(TemplateView):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('core:login')
        return redirect('core:store_list_view')


class LoginView(TemplateView):
    template_name = 'core/pages/login.html'

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            django_login(request, user)
            return redirect('core:store_list_view')
        messages.error(request, 'Login ou senha inválida')
        return redirect('core:login')

class LogoutRedirectViews(RedirectView):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('core:redirect_authentication')

class StoreListView(LoginRequiredMixin, SearchableListMixin, ListView):
    model = Company
    template_name = 'core/pages/store/list.html'
    search_fields = ['name', 'owner__name', ]

    def get_context_data(self, **kwargs):
        context = super(StoreListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q') if self.request.GET.get('q') else ''
        return context


class ImportFileCreateView(LoginRequiredMixin, View):
    success_url = reverse_lazy('core:store_list_view')

    def get(self, request, *args, **kwargs):
        return redirect('core:store_list_view')

    def post(self, request, *args, **kwargs):
        ImportCNAB.objects.create(file=request.FILES.get('importFile'))
        messages.success(request, 'Arquivo importando com sucesso!')
        return HttpResponseRedirect(self.success_url)

core/templates/core/base.html
{% load i18n l10n static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% trans 'Desafio' %}</title>
    <link href="{% static 'core/base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">
    <link href="{% static 'core/base/css/sb-admin-2.min.css' %}" rel="stylesheet">
    {% block extra_css %}
    {% endblock %}


</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    {% include 'core/components/menu.html' %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                {% include 'core/components/navbar.html' %}
            </nav>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">
                {% block content %}


                    <!-- /.container-fluid -->
                {% endblock %}

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->

            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">{% trans 'Deseja realmente sair do sistema?' %}</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">{% trans 'Cancelar' %}</button>
                    <a class="btn btn-primary" href="{% url 'core:logout' %}">{% trans 'SAIR' %}</a>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'core/base/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'core/base/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <script src="{% static 'core/base/js/sb-admin-2.min.js' %}"></script>


    {% block extra_js %}
    {% endblock %}
    <!-- Page level plugins -->

</body>

</html>

core/templates/core/components/menu.html
{% load i18n l10n static %}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">{% trans 'Desafio' %}</div>
    </a>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
        <a class="nav-link">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>{%  trans 'Menu' %}</span></a>
    </li>
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Charts -->
    <li class="nav-item active">
        <a class="nav-link" >
            <i class="fas fa-fw fa-chart-area"></i>
            <span>{% trans 'Empresa' %}</span></a>
    </li>


</ul>

core/templates/core/components/modal/modal_import.html
{% load i18n l10n static %}
<div class="modal fade" id="importModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{% url 'core:store_import_create_view' %}"
                  method="post"
                  id="import_form_id"
                  enctype="multipart/form-data"
                  {% if form_submitted %}class="was-validated" {% endif %}>
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                        <div class="row">
                            <input type="file"  required name="importFile" class="btn btn-primary col-md-12"  >
                        </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">{% trans 'Cancelar' %}</button>
                    <button type="submit" class="btn btn-primary">{% trans 'Importar Arquivo' %}</button>
                </div>
            </form>
        </div>
    </div>
</div>

core/templates/core/components/navbar.html
{% load i18n l10n static %}
<ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
   

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
            <img class="img-profile rounded-circle"
                 src="{% static 'core/base/img/undraw_profile.svg' %}">
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
             aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Settings
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                Activity Log
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
            </a>
        </div>
    </li>

</ul>

core/templates/core/pages/login.html
{% load i18n l10n static %}
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% trans 'Login' %}</title>

    <link href="{% static 'core/base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    {#    <link#}
    {#            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"#}
    {#            rel="stylesheet">#}
    <link href="{% static 'core/base/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
<div class="container">
    <div class="row ">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="p-5">
                                <div class="text-center">

                                    <h1 class="h4 text-gray-900 mb-4">{% trans 'Bem-Vindo' %}</h1>
                                </div>
                                <form class="user" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="username" name="username" class="form-control form-control-user"
                                               id="input" aria-describedby="emailHelp"
                                               placeholder="{% trans 'Login' %}">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" class="form-control form-control-user"
                                               id="inputPassword" placeholder="{% trans 'Senha' %}">
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-user btn-block">
                                        {% trans 'Login' %}
                                    </button>
                                </form>
                                <hr>
                                {% for message in messages %}
                                    <div class="row">
                                        <div class="card bg-danger text-white col-md-12">
                                            <div class="card-body text-center">
                                                {{ message }}
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

<script src="{% static 'core/base/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'core/base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'core/base/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'core/base/js/sb-admin-2.js' %}"></script>
</body>

</html>

core/templates/core/pages/store/list.html
{% extends 'core/base.html' %}
{% load i18n l10n static %}

{% block extra_css %}
    <link href="{% static 'core/base/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    {% include 'core/components/modal/modal_import.html' %}

    <!-- Page Heading -->

    <div class="col-sm-12 col-xs-12">
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible show m-t-lg m-b-none"
                 role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{% trans 'Empresas' %}</h1>
        <a class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"
           data-toggle="modal" data-target="#importModal"
        ><i
                class="fas fa-download fa-sm text-white-50" style="margin-right: 10px"></i>{% trans 'Importar novo aquivo' %}</a>
    </div>
    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-md-4 " style="margin-bottom: 16px">
            <form method="GET">
                <div class="input-group">
                    <input type="text" value="{{ q }}" name="q" class="form-control bg-white border-0 small" placeholder="{% trans 'Buscar por Empresa ou Empresário' %}" aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="card shadow mb-4">

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable2" width="100%" cellspacing="0">
                    <thead class="btn-primary">
                    <tr>
                        <th>{% trans 'Empresa' %}</th>
                        <th>{% trans 'Empresário' %}</th>
                        <th>{% trans 'Total Importações' %}</th>
                        <th>{% trans 'Total Entradas' %}</th>
                        <th>{% trans 'Total Saídas' %}</th>
                        <th>{% trans 'Saldo em Conta' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for company in object_list %}
                        <tr>
                            <td>{{ company.name }}</td>
                            <td>{{ company.owner.name }}</td>
                            <td>{{ company.total_imports }}</td>
                            <td>{{ company.total_in }}</td>
                            <td>{{ company.total_out }}</td>
                            <td>R$: {{ company.total_balance|floatformat:2 }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}


{% block extra_js %}
    <script src="{% static 'core/base/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'core/base/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'core/base/js/demo/datatables-demo.js' %}"></script>
    <script>
        $('#dataTable2').DataTable({
            searching: false,
            language: {
                "sEmptyTable": "Nenhum registro encontrado",
                "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                "sInfoPostFix": "",
                "sInfoThousands": ".",
                "sLengthMenu": "_MENU_ resultados por página",
                "sLoadingRecords": "Carregando...",
                "sProcessing": "Processando...",
                "sZeroRecords": "Nenhum registro encontrado",
                "sSearch": "Pesquisar",
                "oPaginate": {
                    "sNext": "Próximo",
                    "sPrevious": "Anterior",
                    "sFirst": "Primeiro",
                    "sLast": "Último"
                },
            },
        });

        {#"language": {#}
        {#"sProcessing":    "Procesando...",#}
        {#"sLengthMenu":    "Mostrar _MENU_ registros",#}
        {#"sZeroRecords":   "No se encontraron resultados",#}
        {#"sEmptyTable":    "Ningún dato disponible en esta tabla",#}
        {#"sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",#}
        {#"sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",#}
        {#"sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",#}
        {#"sInfoPostFix":   "",#}
        {#"sSearch":        "Buscar:",#}
        {#"sUrl":           "",#}
        {#"sInfoThousands":  ",",#}
        {#"sLoadingRecords": "Cargando...",#}
        {#"oPaginate": {#}
        {#    "sFirst":    "Primero",#}
        {#    "sLast":    "Último",#}
        {#    "sNext":    "Siguiente",#}
        {#    "sPrevious": "Anterior"#}
        {# },#}
    </script>
{% endblock %}